# Generated by Django 2.1.4 on 2019-01-24 13:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileinfo',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='node',
            old_name='temperature',
            new_name='TEMP',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='gl',
            new_name='g1',
        ),
        migrations.AddField(
            model_name='node',
            name='dist',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='ACC',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='G4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='GPS',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.AlterField(
            model_name='node',
            name='T',
            field=models.CharField(max_length=200),
        ),
    ]
