# Generated by Django 2.1.4 on 2019-01-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190103_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='gl',
            new_name='g1',
        ),
    ]
