# Generated by Django 2.1.4 on 2019-01-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190103_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='temperature',
            new_name='TEMP',
        ),
    ]
