# Generated by Django 2.1.4 on 2019-01-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190103_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileinfo',
            options={'ordering': ['id']},
        ),
    ]
