# Generated by Django 2.1.4 on 2019-01-06 22:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20190106_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='GPS',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
