# Generated by Django 2.1.4 on 2019-01-07 17:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20190106_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='GPS',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326),
        ),
    ]
