# Generated by Django 2.1.4 on 2019-01-07 17:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20190107_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='GPS',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
